name: Build KernelSU Next Boot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y curl unzip wget

    - name: Download magiskboot
      run: |
        wget https://github.com/topjohnwu/Magisk/releases/latest/download/magiskboot -O magiskboot
        chmod +x magiskboot

    - name: Check file
      run: ls -l

    - name: Unpack
      run: ./magiskboot unpack input/init_boot.img

    - name: Patch KernelSU Next
      run: |
        curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/main/kernel/setup.sh | bash -

    - name: Repack
      run: ./magiskboot repack input/init_boot.img

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: patched_boot
        path: new-boot.img
